# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
    ]
