# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_staff_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='realname',
        ),
    ]
